"""Non-configurable constants and magic numbers."""

# Chunking
MIN_CHUNK_LENGTH = 20
MAX_REPETITION_RATIO = 0.5

# Near-duplicate detection
NEAR_DUP_SIMILARITY_THRESHOLD = 0.95
MINHASH_NUM_PERM = 128

# Query decomposition
MAX_SUB_QUESTIONS = 5

# Verification
VERIFICATION_MAX_RETRIES = 2
SELF_CONSISTENCY_TEMPERATURE = 0.7

# BM25 tokenizer
STOPWORDS = frozenset(
    {
        "a",
        "an",
        "the",
        "and",
        "or",
        "but",
        "in",
        "on",
        "at",
        "to",
        "for",
        "of",
        "with",
        "by",
        "from",
        "is",
        "it",
        "this",
        "that",
        "are",
        "was",
        "were",
        "be",
        "been",
        "being",
        "have",
        "has",
        "had",
        "do",
        "does",
        "did",
        "will",
        "would",
        "could",
        "should",
        "may",
        "might",
        "shall",
        "can",
        "not",
        "no",
        "nor",
        "so",
        "as",
        "if",
        "then",
        "than",
        "too",
        "very",
        "just",
        "about",
        "above",
        "after",
        "again",
        "all",
        "also",
        "am",
        "any",
        "because",
        "before",
        "between",
        "both",
        "each",
        "few",
        "he",
        "her",
        "here",
        "him",
        "his",
        "how",
        "i",
        "into",
        "its",
        "me",
        "more",
        "most",
        "my",
        "now",
        "only",
        "other",
        "our",
        "out",
        "over",
        "own",
        "same",
        "she",
        "some",
        "such",
        "their",
        "them",
        "there",
        "these",
        "they",
        "through",
        "under",
        "up",
        "us",
        "we",
        "what",
        "when",
        "where",
        "which",
        "while",
        "who",
        "whom",
        "why",
        "you",
        "your",
    }
)

# Tiktoken encoding for OpenAI models
TIKTOKEN_ENCODING = "cl100k_base"
