"""Protocol for document storage."""

from __future__ import annotations

from typing import Protocol

from rag_engine.models.domain import Chunk, Document


class DocumentStore(Protocol):
    async def save_document(self, doc: Document) -> str: ...

    async def save_chunks(self, chunks: list[Chunk]) -> None: ...

    async def get_document(self, doc_id: str) -> Document | None: ...

    async def get_chunk(self, chunk_id: str) -> Chunk | None: ...

    async def get_chunks_by_doc(self, doc_id: str) -> list[Chunk]: ...

    async def get_all_chunks(self) -> list[Chunk]: ...

    async def count_documents(self) -> int: ...

    async def count_chunks(self) -> int: ...
